### ISSUE TITLE
Requirement Issue

### ISSUE THREAD

**Issue by xian627** [xian627/NVIC#1]
It's working on my side. Please try again.

**Comment by vlad-nicula** [comment]
okay i see.

**Comment by vlad-nicula** [comment]
plz remove files and this comment.

**Comment by xian627** [comment]
I already gave you that number. And you can call cm respectively.
Please let me know how I can touch you freely.

**Comment by xian627** [comment]
please let me know another one.

**Comment by xian627** [comment]
Honestly, i can't understand what you mean exactly. Is it real or just show?

**Comment by vlad-nicula** [comment]
it's just a show :)
there should many messages related with project.
i called head and here's his answer.
they removed all the files except of NVIC.xlsxm file so can't check Account.xlsx at the moment.
he wants to have other files that you promised to send again, and detailed spec that you discussed with the client.
about cm, i should do it later.

**Comment by xian627** [comment]
Thanks for your trying. I'd like you to solve cm issue soon.

**Comment by vlad-nicula** [comment]
sure

**Comment by xian627** [comment]
what issue happened to your account? have you tried to solve cm issue today?

**Comment by xian627** [comment]
what's the status of my issue?

**Comment by vlad-nicula** [comment]
i still didn't solve that issue.
And I can't get online here for around 2 weeks from now on.
Will ping you when I get back. Don't worry.

**Comment by xian627** [comment]
ufff, what happened?

**Comment by vlad-nicula** [comment]
it's 0.2G which i can't easily upload here.

**Comment by vlad-nicula** [comment]
i'm leaving today and will get back after 2~3 weeks.

**Comment by vlad-nicula** [comment]
hi, https://mega.nz/fm/WDowDTxY plz check this url

**Comment by vlad-nicula** [comment]
plz

**Comment by xian627** [comment]
Thanks for your help. What is sr issue? And I can't see anything in that link.

**Comment by xian627** [comment]
Thanks for your help, but I can't see anything in that link. What's the sr issue? I hope you got back asap.

**Comment by vlad-nicula** [comment]
https://yadi.sk/d/pToX7mEi3WeLeu

**Comment by vlad-nicula** [comment]
plz check this one.

**Comment by xian627** [comment]
Btw, what do you mean sr issue?

**Comment by xian627** [comment]
Is this what cm gave to you?

**Comment by vlad-nicula** [comment]
yes. cm gave 2

**Comment by vlad-nicula** [comment]
lemme know if down is completed.

**Comment by xian627** [comment]
yes it's completed

**Comment by vlad-nicula** [comment]
good

**Comment by xian627** [comment]
What do you mean SR issue?

**Comment by vlad-nicula** [comment]
dunno. that's from a female. cm gave me

**Comment by vlad-nicula** [comment]
you mentioned about it before?

**Comment by xian627** [comment]
Ah, got it

**Comment by xian627** [comment]
thanks. btw when do you back completely?

**Comment by xian627** [comment]
Did cm gave you delicious food?

**Comment by vlad-nicula** [comment]
dunno. i'll leave today. Nope :)

**Comment by xian627** [comment]
Hmmm, I hope you get back soon. Hope everything will go well on your side.

**Comment by vlad-nicula** [comment]
okay. take care.

**Comment by vlad-nicula** [comment]
btw, you don't send my $? why did you take it without my agreement?

**Comment by xian627** [comment]
what do you mean my $?

**Comment by vlad-nicula** [comment]
you brought my $ from my bag?

**Comment by vlad-nicula** [comment]
0.3k

**Comment by xian627** [comment]
no, are you kidding me?

**Comment by vlad-nicula** [comment]
aunt told me so.

**Comment by xian627** [comment]
what? i'm very confused

**Comment by vlad-nicula** [comment]
lemme know if she's telling a fraud... did you take $ from her & mum?

**Comment by xian627** [comment]
yes i took from her & mum, but i didn't take it out from your bag

**Comment by vlad-nicula** [comment]
she said that you also took from my wallet in my bag.

**Comment by vlad-nicula** [comment]
ooops.
i see.
will ask her again.

**Comment by xian627** [comment]
no no i don't check other's bag myself.

**Comment by vlad-nicula** [comment]
i see.

**Comment by xian627** [comment]
and please tell ma as i'm finding out the guy who can carry it safely for now. If i can't find it out until my lab head coming here, i will send it with him. ok?

**Comment by vlad-nicula** [comment]
okay

**Comment by xian627** [comment]
and I'm sending thankful regards about she called cm herself and asking several things. maybe cm will send her bday greeting and present on her bday.

**Comment by vlad-nicula** [comment]
i see. what did she ask to cm?

**Comment by xian627** [comment]
like whether she is doing well, and crying or not blablabla

**Comment by vlad-nicula** [comment]
cm calls you as professor ms :)

**Comment by vlad-nicula** [comment]
i see,

**Comment by xian627** [comment]
how does she call you?

**Comment by vlad-nicula** [comment]
nothing special. just hello.

**Comment by vlad-nicula** [comment]
i told cm not to tell anybody even to ma

**Comment by xian627** [comment]
got it, well done

**Comment by vlad-nicula** [comment]
i see

**Comment by xian627** [comment]
hope everything will go well on your side. and i hope next communication will be done soon. have a great day

**Comment by vlad-nicula** [comment]
okay, see you. take care.

**Comment by vlad-nicula** [comment]
Hi, I'm back.

**Comment by vlad-nicula** [comment]
I'll remove my comment myself. Do not remove it yourself.

**Comment by xian627** [comment]
Oh, you got back totally. Nice! I got it. How's your days going? Is everything going well? How was mm's bday?

**Comment by vlad-nicula** [comment]
I've been to somewhere to get proved by others for solving our house problem(uc's academy). I'll ping you if there's a great news.

**Comment by vlad-nicula** [comment]
cm went to srw house to celebrate mm's bday. bday presents were a small box of genuine flowers & a cosmetic set & many delicious dishes :)
mm seems fully satisfied on bday. hehe

**Comment by xian627** [comment]
One question. So is that investigation get started?

**Comment by vlad-nicula** [comment]
i'm working with alex now. Haha, it's finished!

**Comment by vlad-nicula** [comment]
We're waiting for the final decision every day.

**Comment by vlad-nicula** [comment]
Don't you have any project for me?

**Comment by xian627** [comment]
Not for now. As soon as I get, I will let you know.

**Comment by vlad-nicula** [comment]
it seems that you're super busy or under strict surveillance nowadays.

**Comment by xian627** [comment]
Not so, but what's up?

**Comment by xian627** [comment]
btw, where do you work now?

**Comment by vlad-nicula** [comment]
because you're not calling me often :)
i'm working in where you visited.

**Comment by xian627** [comment]
Got it, I don't want to bother you. Just I hope your help regarding CM issue one or two times monthly.

**Comment by vlad-nicula** [comment]
i see.

**Comment by xian627** [comment]
Did you do what I asked?

**Comment by vlad-nicula** [comment]
nope. do you want paper let?

**Comment by xian627** [comment]
No i don't want it, but you need to explain it asap because sometime it will be needed for just show to the bosses that he's missing me very much. This is necessary. But that has to be written in formal word. If not, it would be very bad to me lol. Make sense?

**Comment by xian627** [comment]
By the way, How's your work going related with becoming officer? I'd like you to solve cm issue within today.

**Comment by vlad-nicula** [comment]
i see. i'll solve that issue within tomorrow. it's midnight here :)

**Comment by xian627** [comment]
Ok thanks

**Comment by xian627** [comment]
Did you solve the issue?

**Comment by vlad-nicula** [comment]
yes, i did. he said "of course, i know it". :) he also would like you not to tell our mm that he contacts with you via file. And also if you write let, tell there that he sent a photo taken with our pas and that he didn't write any letter yet.

**Comment by xian627** [comment]
Ok got it. Thanks for your help. How's everything going?

**Comment by vlad-nicula** [comment]
hehe, things are going so so.
And one great news! Our house problem has been fully resolved! It'll be announced this week.

**Comment by xian627** [comment]
Oh really? Awesome!

**Comment by xian627** [comment]
Btw, how is cm calling you as?

**Comment by vlad-nicula** [comment]
Yes, really!!! That fucking issue will be removed from our cadre documents forever! We're now new persons! Haha~ But still waiting for the announcement.
Never used a word for calling me. Just "hi, how are you? i'm cm." - this is always the same :)

**Comment by vlad-nicula** [comment]
ftp://geom.geometrics.com/pub/GeoElectric/Presentations/OhmMapper_May_2009.ppt
ftp://geom.geometrics.com/pub/GeoElectric/DataSheets/OhmMapper_Spec_Sheet.pdf
ftp://geom.geometrics.com/pub/GeoElectric/Manuals/OhmMapper-Manual-TRN-2004.PDF
ftp://geom.geometrics.com/pub/GeoElectric/Literature/OhmMapper-cases.pdf
ftp://geom.geometrics.com/pub/GeoElectric/Literature/Report-CPOMdraft1.pdf

Could you please download these files and upload them here?
We can't use ftp here.

**Comment by xian627** [comment]
Just I tried to download those, but it's not working here as well. Is there any other links?

**Comment by vlad-nicula** [comment]
no other links available.
they're ftp.
http://www.geometrics.com/geometrics-products/geometrics-electro-magnetic-products/electro-magnetic-information-and-case-studies/

they're all listed here. You can just search for those with the word of "OHM".
Device name is: ohm mapper

**Comment by vlad-nicula** [comment]
And please don't forget to send $ with your room head when he returns.

**Comment by xian627** [comment]
I pushed the required files and I don't forget it :) Can you remove all comments and open another issue?

**Comment by vlad-nicula** [comment]
sure.
