### ISSUE TITLE
Newest issues

### ISSUE THREAD

**Issue by xian627** [xian627/NVIC#3]

**Comment by vlad-nicula** [comment]
hi
https://www.dropbox.com/s/pljmbbzhjaz58mh/New%20folder.rar?dl=0

**Comment by vlad-nicula** [comment]
if you download the issue, let me know here.

**Comment by xian627** [comment]
Thanks for your help. Just I got the solved issues.

**Comment by vlad-nicula** [comment]
let me have a look at the picture of the shirt you bought for me. :)

**Comment by xian627** [comment]
Ok got it.

**Comment by xian627** [comment]
Btw, was it announced?

**Comment by vlad-nicula** [comment]
Not yet announced. They say that they're making a plan how to announce it meaningfully & worth educational & impressive.

**Comment by xian627** [comment]
got it

**Comment by xian627** [comment]
How are you doing?

**Comment by vlad-nicula** [comment]
i'm doing okay...
btw, how are you doing? And why don't you send me the photo of shirt? When will they return?

**Comment by vlad-nicula** [comment]
Urgent! could you plz give me astrill vpn credential now?

**Comment by xian627** [comment]
Just uploaded, please check it and let me know if everything is good.
and that shirt is coming now.

**Comment by xian627** [comment]
Did you get it?

**Comment by vlad-nicula** [comment]
ah, i see:)

**Comment by vlad-nicula** [comment]
no call.

**Comment by vlad-nicula** [comment]
Just had a call from cm. Plz ask senders not to pack big files such as images & videos that are not mandatory to send.(seems like you bring photos of kids of someone?)
Also, when are they returning? Will they contact me as soon as arrive here?(not aunt)

**Comment by xian627** [comment]
Ok got it, and they will return on tomorrow. They will contact with mm directly.

**Comment by xian627** [comment]
And I will make sure not sending big things for sure. Sorry about it.

**Comment by vlad-nicula** [comment]
Hi, mm will also tell them to contact with me.

So, plz tell him to contact with me directly.
Also, will they bring sth for me & cm? 
Today, cm did a great job for me :) He brought lots of snack for me...

Please check the updates.
https://www.dropbox.com/s/x1ojvrkl620sga9/New%20folder.rar?dl=0

Let me know as soon as you get that.

**Comment by xian627** [comment]
Hehe That’s what I let him. You may feel thanks to me. By the way I am sending shirts for you but not for cm. Because mm doesn’t like it lol. I will do it as soon as I get back to work. Thanks

**Comment by xian627** [comment]
omg, just I checked the material but he said as he thought about snacks before himself lol. we were on same page. haha

**Comment by xian627** [comment]
They left yesterday but I could just sent your shirt since sb let me not send by them. Because it can be said as i'm making so much money here and it's not good for me. I'll do my best to make it reach there asap by other's hand. No worries.

**Comment by vlad-nicula** [comment]
I see.

**Comment by vlad-nicula** [comment]
didn't you send sandal?

**Comment by xian627** [comment]
Did you get things by your hand?

**Comment by vlad-nicula** [comment]
Yes, thank you. They suit me perfectly. BTW, striped one is not a welcome. It makes me childish... Also, instead of that, I was expecting an official shirt. Anyway thanks. I also heard from nh that cm sent you some packs of cigars, right? How many packs?

**Comment by xian627** [comment]
5 packs and eyedrop :) I wrote that in the let and suggested to have wed. ceremony in next fall. I hope you would help me to make mm agree about it.

**Comment by vlad-nicula** [comment]
i see. :)

**Comment by xian627** [comment]
By the way, isn't it announced yet? And didn't you get any call from my room head?

**Comment by xian627** [comment]
you there?

**Comment by xian627** [comment]
How're you doing?

**Comment by xian627** [comment]
Hi

**Comment by vlad-nicula** [comment]
yep, super busy nowadays...

**Comment by xian627** [comment]
oh, i thought as something happened to you. any other news?

**Comment by vlad-nicula** [comment]
no news

**Comment by xian627** [comment]
question. why is that taking so long to be announced?

**Comment by xian627** [comment]
and let me know mm's reaction after get my let. thanks

**Comment by xian627** [comment]
btw, mm got award patriot award?

**Comment by xian627** [comment]
seemed like you're ignoring me in these days. hmmm

**Comment by vlad-nicula** [comment]
hh. it was announced and i knew it yesterday :) also patriot award will be awarded in Aug hopefully...

**Comment by xian627** [comment]
oh great! can you solve cm issue in this weekend once more?

**Comment by vlad-nicula** [comment]
sure!

**Comment by xian627** [comment]
How are you doing? just i uploaded cm issue, please solve that issue asap and let me know the reaction of mm. btw didn't you get call from my room head? if not, please try to call him and ask whether how's everything going on my job. I'd like you to do all of this asap. Thanks.

**Comment by xian627** [comment]
because it's very urgent to me regarding room head, so i hope you solve that issue asap.

**Comment by xian627** [comment]
you there?

**Comment by vlad-nicula** [comment]
i see.

**Comment by xian627** [comment]
did you get cm issue? if you get it let me know. And please let me know the reaction of mm and solve r-head issue also. Thanks

**Comment by xian627** [comment]
you there? any replies?

**Comment by xian627** [comment]
did you solve all issues?

**Comment by xian627** [comment]
ufff you there? seemed like you are super busy and you don't want me in these days.

**Comment by vlad-nicula** [comment]
hehe. https://yadi.sk/d/gnZEMnD03Zp9CB
here's the updated version of cm issue.

**Comment by vlad-nicula** [comment]
busy & not good condition & strict...

**Comment by vlad-nicula** [comment]
r head told me that they're working on it but didn't make a substantial progress as they're super busy...

**Comment by vlad-nicula** [comment]
I persuaded mm to discuss with cm's ps... will let you know the result.

**Comment by xian627** [comment]
Thanks you for your help. You are my eyes. Thanks again!

**Comment by xian627** [comment]
Hey how are you doing? can you solve cm issue in next week? maybe on Tuesday or Wednesday

**Comment by vlad-nicula** [comment]
sure.

**Comment by vlad-nicula** [comment]
spending busy days...

**Comment by xian627** [comment]
Let me know once you get the issue. Thanks

**Comment by vlad-nicula** [comment]
i got it.

**Comment by vlad-nicula** [comment]
if u have an upk client acct, plz give me a small task so that i can get at least one review.

**Comment by xian627** [comment]
honestly i don't have one myself, but i will find someone else who can do this. By the way, let me know your acct info so that i can send direct invite when i get ready

**Comment by vlad-nicula** [comment]
sure.

**Comment by vlad-nicula** [comment]
also, cm asks if you can go to meet the wife of his father's elder brother...or if she should go to meet you.
he's gonna send sth with her...

**Comment by xian627** [comment]
i can go myself

**Comment by vlad-nicula** [comment]
yeah, it's going smoothly atm. we had a dinner together at the restaurant you were going around 10 days ago. and he brought beer & kao ya today :) i'll update issue soon.

**Comment by vlad-nicula** [comment]
here our guys say that he's their sister in law! haha :)

**Comment by vlad-nicula** [comment]
also, wife of his dd's elder bro will call you once she gets there. then you should go there :)

**Comment by vlad-nicula** [comment]
hehe. went 10 days ago not yesterday. had no time to tell you about it before...

**Comment by vlad-nicula** [comment]
issue uploaded here.

**Comment by xian627** [comment]
thanks, i got it. btw he asked whether mm didn't mention nothing about wedd. he told me as his mm called my mm and asked to do it in next year, but nothing heard about it yet. I'd like to know that.

**Comment by vlad-nicula** [comment]
will ask about it. btw, i need your help. i gotta pay 0.6 thousand to an address but can't use our p. i hope you do that and get paid for it from ours. should be done today. possible? it'd be better if it's us p. also need your favor regarding to uk acct.

**Comment by xian627** [comment]
I can't understand your requirement clearly.

**Comment by xian627** [comment]
By the way, you may remove the last one. Thanks for your help.

**Comment by vlad-nicula** [comment]
i mean, i need your help to borrow your pp acct tonight. can you be able to talk tonight? via where??

**Comment by xian627** [comment]
Can we have discussion now?

**Comment by vlad-nicula** [comment]
yes, on sk?

**Comment by vlad-nicula** [comment]
did you solve my issue?

**Comment by xian627** [comment]
I'm trying to touch my clients from this morning, but they don't reply since they are on vacation for now. Very difficult to touch them in these days.

**Comment by vlad-nicula** [comment]
check https://www.dropbox.com/s/mgbatv47exxikpk/NVIC.zip?dl=0
room head wants a kinda structured spec.

**Comment by xian627** [comment]
Ok thanks for your help and i will solve the acct issue in next week.

**Comment by vlad-nicula** [comment]
great. thanks.

**Comment by xian627** [comment]
You're welcome. By the way, did you ask to mm?

**Comment by xian627** [comment]
I'm sending my regards to dd today.

**Comment by vlad-nicula** [comment]
thanks. cm will go with me :)

**Comment by xian627** [comment]
Sounds good.

**Comment by vlad-nicula** [comment]
we've celebrated the bday memorably. cm & cm's dd & aunt & i have been to SR. it was a good day :)

**Comment by xian627** [comment]
sounds good. anything new to me? when did you come back?

**Comment by vlad-nicula** [comment]
hi, updated...

**Comment by vlad-nicula** [comment]
when can you solve uk issue??

**Comment by xian627** [comment]
just i got the issue, but i can't find your uk acct on upwk. Can you confirm the account name again?

**Comment by vlad-nicula** [comment]
great!!! thank you.
Happy Birthday~~~
Wish your good health & success :)

There'd be great news coming soon... hehe

**Comment by xian627** [comment]
Thank you! What a great news do you mean?

**Comment by xian627** [comment]
will update in this weekend. thanks

**Comment by xian627** [comment]
you mean the pat. award? hehe

**Comment by vlad-nicula** [comment]
when can i get updates regarding to the uk help??

**Comment by xian627** [comment]
i'm waiting for my client who can help on that issue. btw, you're always avoiding to reply my questions. hmmm~

**Comment by xian627** [comment]
ok got it, i will submit cm issue on sunday night or monday. please put a call to him. thanks.

**Comment by vlad-nicula** [comment]
hi, did you enjoy your bday with your guys??? where's a new issue doc?

**Comment by vlad-nicula** [comment]
cm is looking forward to that....got calls many times already :)

**Comment by xian627** [comment]
I will post it tonight for sure. sorry for late update.

**Comment by vlad-nicula** [comment]
what about answer to room head??

**Comment by xian627** [comment]
i will prepare it until tomorrow too

**Comment by xian627** [comment]
i will update early this morning for sure like in 3~4 hours and uk issue is still have some issues. I'm trying to solve it for now. No worries

**Comment by xian627** [comment]
just update issue here.
https://www.dropbox.com/s/36a6cg4yjvi91zd/Komi.rar?dl=0

**Comment by xian627** [comment]
can you get update from up asap like at least until this Fri? i will update room issue tonight

**Comment by xian627** [comment]
did you get the issue?

**Comment by vlad-nicula** [comment]
yes, sure. i'll ask cm. yeah, i got them.
when will the uk issue solution come??

**Comment by vlad-nicula** [comment]
you don't update rm issue?

**Comment by xian627** [comment]
still discussing with client regarding the rm issue, and uk issue didn't solve yet. let me solve it urgently this week.

**Comment by xian627** [comment]
i have one other requirement to you. tmr is cm's mm's bday and i'd like you to call him instead of me and send my regards as well. make sense?

**Comment by vlad-nicula** [comment]
sure. you mean, 6th Sep? if so, lemme go to the house and send your regards on the spot :)

**Comment by xian627** [comment]
Yes it's 6th sep. i think it will be not held in the house so you need to contact with cm and discuss about it. make sense?

**Comment by vlad-nicula** [comment]
okay sure!

**Comment by vlad-nicula** [comment]
just updated the issue!

**Comment by xian627** [comment]
Thanks for your quick update!

**Comment by vlad-nicula** [comment]
plz let me have updates for rm issue and uk issue.

**Comment by xian627** [comment]
ok sure, i will update as soon as i can. how was yesterday? did you go or not?

**Comment by vlad-nicula** [comment]
plz remove all the issues. urgent!!
